<?php

declare(strict_types=1);

namespace Atelier\Pattern\Tile;

use Atelier\Pattern\AbstractPattern;
use Atelier\Pattern\Internal\Guard;
use Atelier\Pattern\Internal\Num;
use Atelier\Pattern\Internal\Wrap;
use Atelier\Svg\Element\Shape\RectElement;

/**
 * Herringbone, the bond where every brick is laid against the one before it.
 *
 * A brick is twice as long as it is wide, and each one is paired with a brick
 * turned a quarter and set at its end. That L covers four squares of the half
 * brick unit, and the lattice of L positions is generated by (3, 1) and (-1, 1)
 * in those units.
 *
 * That lattice contains (4, 0) and (0, 4), so the tile is four units square and
 * holds exactly four pairs, at (0, 0), (3, 1), (2, 2) and (1, 3). Sixteen unit
 * squares of tile against sixteen of brick: the bond covers the tile once, with
 * nothing over and nothing missing.
 */
final class Herringbone extends AbstractPattern
{
    private function __construct(
        private readonly float $length,
        private readonly float $gap,
    ) {
    }

    /**
     * @param float $length long side of one brick, twice its width
     * @param float $gap    mortar left between two bricks, at most a quarter of the length
     */
    public static function create(float $length = 24.0, float $gap = 1.6): self
    {
        Guard::positive($length, 'length');
        Guard::between($gap, 0.0, $length / 4, 'gap');

        return new self($length, $gap);
    }

    public function tileWidth(): float
    {
        return 2 * $this->length;
    }

    public function tileHeight(): float
    {
        return 2 * $this->length;
    }

    protected function shapes(): array
    {
        $unit = $this->length / 2;
        $inset = $this->gap / 2;
        $long = $this->length - $this->gap;
        $short = $unit - $this->gap;

        $shapes = [];

        foreach ([[0, 0], [3, 1], [2, 2], [1, 3]] as [$column, $row]) {
            $x = $column * $unit;
            $y = $row * $unit;

            // The pair: one brick lying down, one standing at its end.
            $bricks = [
                [$x + $inset, $y + $inset, $long, $short],
                [$x + $this->length + $inset, $y + $inset, $short, $long],
            ];

            foreach ($bricks as [$left, $top, $width, $height]) {
                $offsets = Wrap::offsets($left, $top, $left + $width, $top + $height, $this->tileWidth(), $this->tileHeight());

                foreach ($offsets as [$dx, $dy]) {
                    $brick = new RectElement();
                    $brick->setX(Num::format($left + $dx));
                    $brick->setY(Num::format($top + $dy));
                    $brick->setWidth(Num::format($width));
                    $brick->setHeight(Num::format($height));

                    $shapes[] = $this->painted($brick);
                }
            }
        }

        return $shapes;
    }

    protected function geometry(): array
    {
        return [$this->length, $this->gap];
    }

    protected function slug(): string
    {
        return 'herringbone';
    }
}
